### ISSUE TITLE
Makefile: incorrect syntax handling hashtag (#) symbols

### ISSUE THREAD

**Issue by aeschli** [fadeevab/make.tmbundle#1]
From https://github.com/Microsoft/vscode/issues/60030, reported by @Artalus

![image](https://user-images.githubusercontent.com/10381253/46543321-35b77f80-c8c9-11e8-8398-984f7f3a063d.png)

As the comment says, '#' symbols do not mark comments when put in quotes.

**Comment by fadeevab** [comment]
I see, I need time to get involved.
