### ISSUE TITLE
Wrong tokenization of else statement for ifdef in Makefile

### ISSUE THREAD

**Issue by alexr00** [fadeevab/make.tmbundle#10]
Issue Type: <b>Bug</b>

In this Makefile sample "else" statement gets a wrong color:

```
a := 1
target:
ifdef a
	echo a
else
	echo b
endif
```
Originally from @foreignmeloman  in https://github.com/microsoft/vscode/issues/109008

Screenshot:
![image](https://user-images.githubusercontent.com/11769352/96580534-797f5500-12e9-11eb-983d-f1acf2d1a0cf.png)

VS Code version: Code - Insiders 1.51.0-insider (13b3c937dc5e3816c79bdd2cdf2cdf6f9c727b75, 2020-10-20T06:07:53.466Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (4.73GB free)|
|Process Argv|--crash-reporter-id b24ee7a9-a4c3-4313-b1c0-661cd65ffc34|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by fadeevab** [comment]
Thanks for reporting. I'll check it out a bit later.

**Comment by fadeevab** [comment]
Fixed!

Hey, @alexr00, could you return unit-tests for Makefile into vscode repository back? Or could you say where they are. Thank you!

**Comment by alexr00** [comment]
The colorize test fixtures are back in the VS Code repo (ex. https://github.com/Microsoft/vscode/blob/af2bcd4d4612dc25f848a0a6a758507010401fa0/extensions/vscode-colorize-tests/test/colorize-fixtures/makefile#L1-L1). 

The tests can be run same as always with https://github.com/Microsoft/vscode/blob/0e7f3d0d8cbc24b5c72b93838f3cb9be3a22d4ff/scripts/test-integration.sh

**Comment by ofadieiev** [comment]
@alexr00  Your guys have to get back code review practices and other SDLC practices, as I see commits moving huge parts of source code here and there without any description and PR. Folks, you are Microsoft, come on! ;)

**Comment by fadeevab** [comment]
@alexr00 Your guys have to get back code review practices and other SDLC practices, as I see commits moving huge parts of source code here and there without any description and PR. Folks, you are Microsoft, come on! ;)

**Comment by foreignmeloman** [comment]
Thanks for the fix! So when will this be available?

**Comment by fadeevab** [comment]
@foreignmeloman  Usually, we get the update with the very next VSCode release. The changes from this repo have to be pulled to https://github.com/microsoft/vscode/blob/master/extensions/make/syntaxes/make.tmLanguage.json by @alexr00  or somebody else from the VSCode team. Need just wait.

**Comment by alexr00** [comment]
@fadeevab I tried pulling in your changes, but I'm seeing some colorizing results that look unintended. Specifically, when a `#` is preceded by a `tab` then the line doesn't get tokenized as a comment. Example snippet:
```make
	# "$$" in a shell means to escape makefile's variable substitution.
```

**Comment by fadeevab** [comment]
@alexr00 Yeah, I changed the behavior of comments colorizing in the scope of https://github.com/fadeevab/make.tmbundle/issues/4

![image](https://user-images.githubusercontent.com/5967447/107119888-1662ff80-6893-11eb-8b8b-6ae39de2edac.png)

This is because:

```make
target:
# This is a comment of Makefile
<------># This is a comment of Bash, and it is not gonna be colorized. "Bash inside of Makefile" is a difficult deal.
```

@alexr00 I didn't update test because there was no test files at the moment of my patch. I can upgrade test cases later... Still, you can upgrade test results for now.

**Comment by fadeevab** [comment]
@alexr00 Or, if you need, we can wait until I upgrade test case results inside of your test system. What do you think?

**Comment by alexr00** [comment]
@fadeevab no need for you to update the tests, thank you though. I just wasn't sure if this was expected behavior.
