### ISSUE TITLE
Makefile grammar for function call separator syntax

### ISSUE THREAD

**Issue by alexr00** [fadeevab/make.tmbundle#12]
The `,` needs a syntax grammar

<img width="890" alt="Screen Shot 1400-06-15 at 19 11 45" src="https://user-images.githubusercontent.com/2157285/132234624-0b0ea0f7-bb6b-422d-a199-186680abb5a0.png">

Originally from @pouyakary in https://github.com/microsoft/vscode/issues/132473

**Comment by pouyakary** [comment]
@alexr00 thanks for the issue, I implemented this in the #11, hope to be merged soon.

**Comment by fadeevab** [comment]
@alexr00 @pouyakary I did it guys https://github.com/fadeevab/make.tmbundle/commit/fcc4e92f866d568bd53ca0ab17d774479c20fe7e.
