### ISSUE TITLE
Makefile syntax highlighting incorrectly highlights string as comment

### ISSUE THREAD

**Issue by alexr00** [fadeevab/make.tmbundle#14]
Does this issue occur when all extensions are disabled?: Yes

VS Code:
```
Version: 1.65.0-insider
Commit: 50089c3f92c17584a4aca179f51f220b56c22020
Date: 2022-02-14T05:19:23.146Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Linux x64 5.10.0-11-amd64 snap
```

OS: Debian 11

Steps to Reproduce:

1. Open or create a Makefile in Visual Studio Code
2. Insert a string wrapped in quotes that contains a `#`.

For example:
```mk
PASSWORD='jF$rbr*b9uRuTxsUdSH38jo5wcAYQXp3fn7#uU^3BJUGEeycV4ziS*h7V&m6bh^VKN24Q^&rF'
```

Everything after the `#` is highlighting as a comment, but this is actually part of the string. (Wrapped in `'` to avoid any processing in bash due to special characters like `$`.)

Originally from @[SethFalco](https://github.com/SethFalco) in https://github.com/microsoft/vscode/issues/143272

**Comment by alexr00** [comment]
Possibly related: https://github.com/fadeevab/make.tmbundle/issues/9

**Comment by fadeevab** [comment]
@alexr00 Fixed: https://github.com/fadeevab/make.tmbundle/commit/d22ab907c0c8b8e4c5d0af18723d99838cd31490

 So, actually, this is a correct highlighting (makefile doesn't care about the single quote, it doesn't know it's a "string"):
```make
PASSWORD='jF$rbr*b9uRuTxsUdSH38jo5wcAYQXp3fn7#uU^3BJUGEeycV4ziS*h7V&m6bh^VKN24Q^&rF'
```
HOWEVER, the next example is NOT correctly highlighted ("#" is escaped, thus, must not be treated as a comment):
```make
PASSWORD='jF$rbr*b9uRuTxsUdSH38jo5wcAYQXp3fn7\#uU^......'
```
Now, it's the greatest syntax highlighter for Makefile. 😃

![image](https://user-images.githubusercontent.com/5967447/178083727-39e7aee4-e5ab-4295-84e7-0b3996c482af.png)
