### ISSUE TITLE
Makefile: incorrect syntax handling of comments with prefix

### ISSUE THREAD

**Issue by tbhartman** [fadeevab/make.tmbundle#4]
The comments with prefixes (e.g. `@#`, `+#`, `-#`) below are not highlighted correctly.

```make
clean::
	# this comment is printed during `make clean`
	@# this comment is not printed
	+# this comment is printed but not highlighted correctly
	-# the plus/minus are not meaningful, but should still be handled with comments
	rm -rf dirt
	@# i feel so fresh, so clean, clean
```

Using VS Code, I observe:
![image](https://user-images.githubusercontent.com/896331/61133810-2c78c600-a48c-11e9-9fe1-4378d4bbe989.png)

but expect:
![image](https://user-images.githubusercontent.com/896331/61133845-3dc1d280-a48c-11e9-82de-f6f9fc9ecb14.png)

**Comment by fadeevab** [comment]
@tbhartman I merged PR and I realized one thing:

```makefile
var := aaa
clean:
     # Variable is $(var)
     echo $(var)
```
Guess, what is going to be printed?

```bash
# Variable is aaa
echo aaa
aaa
```
In a statement `# Variable is $(var)` the variable $(var) is not highlighted anymore, instead the whole comment is highlighted. Why the $(var) should be highlighted: because Makefile substitutes $(var) before recipe is interpreted as shell.

I would not revert PR, but with any complaint I could revert a commit.

**Comment by tbhartman** [comment]
@fadeevab I don't believe that is a regression; see #6 and PR #7

**Comment by fadeevab** [comment]
Still I found PR #6 breaks the tests in VSCode

```makefile
echo:
	echo "#" and '#' in quotes are not comments \
		and '\' will be continued
```
With your PR the comment starts from the first # ignoring double-quotes, and it should not happen. We fixed that in other commit before, so I will revert your PR #6, sorry :(. We need to came up with something different.

**Comment by fadeevab** [comment]
FYI, VSCode makefile tests are here: https://github.com/microsoft/vscode/blob/master/extensions/make/test/colorize-fixtures/makefile

I add some new tests from time to time and double-check this repo on VSCode tests.

**Comment by fadeevab** [comment]
@tbhartman I would close all open issues. However, I'd like to ask you, do you have a time and motivation to try the patch which un-colorize the comment in the recipe started with TAB?
```makefile
<------># Comment with $(var)
```

**Comment by fadeevab** [comment]
Fixed! Thank you all.

![image](https://user-images.githubusercontent.com/5967447/107119888-1662ff80-6893-11eb-8b8b-6ae39de2edac.png)
